name: Build and Release PDF

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build PDF
        run: |
          docker run --rm -v "$(pwd)":/workspace -w /workspace texlive/texlive:TL2024-historic bash -c "
              pdflatex main.tex
              biber main
              pdflatex main.tex
              makeindex main
              pdflatex main.tex
          "

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: main-pdf

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf
          tag_name: release-${{ github.run_id }}
          body: |
            Automated release of the PDF compiled from commit ${{ github.sha }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
