name: Build PDF and Publish (Cloudflare R2)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

concurrency:
  group: pdf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    env:
      R2_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      BASE_URL: ${{ secrets.CDN_BASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Install AWS CLI v2
        run: |
          curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
          unzip -q awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          aws --version

      - name: Build PDF
        run: |
          bash build.sh --docker
          test -f main.pdf
          mv main.pdf thesis.pdf
          
      - name: Compute branch-safe name
        id: meta
        # This step will only run if the branch name is NOT 'main'
        if: github.ref_name != 'main'
        run: |
          # Get the branch name, using GITHUB_REF_NAME as a fallback
          BR="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
          # Replace forward slashes with hyphens for a safe file name
          SAFE="${BR//\//-}"
          echo "safe=${SAFE}" >> "$GITHUB_OUTPUT"
          # Define the target PDF name (e.g., thesis-feature-branch.pdf)
          echo "pdf=thesis-${SAFE}.pdf" >> "$GITHUB_OUTPUT"

      - name: Rename PDF (Branch)
        # Only runs if 'meta' ran (i.e., not on main)
        if: github.ref_name != 'main'
        run: mv thesis.pdf "${{ steps.meta.outputs.pdf }}"

      - name: Upload Branch PDF to Cloudflare R2
        id: upload_branch
        # Only runs if 'meta' ran (i.e., not on main)
        if: github.ref_name != 'main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          # The key uses the branch-safe name
          KEY="${{ steps.meta.outputs.pdf }}"
          # The file being uploaded is the one renamed in the previous step
          aws s3 cp "${{ steps.meta.outputs.pdf }}" "s3://${R2_BUCKET}/${KEY}" \
            --endpoint-url "${R2_ENDPOINT}" \
            --content-type application/pdf
          echo "url=${BASE_URL}/${KEY}" >> "$GITHUB_OUTPUT"

      - name: Upload Main PDF to Cloudflare R2
        id: upload_main
        # This step runs ONLY if the branch name IS 'main'
        if: github.ref_name == 'main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: "true"
        run: |
          # Uploads the file 'thesis.pdf' to the fixed key 'thesis.pdf'
          KEY="thesis.pdf"
          aws s3 cp thesis.pdf "s3://${R2_BUCKET}/${KEY}" \
            --endpoint-url "${R2_ENDPOINT}" \
            --content-type application/pdf
          echo "url=${BASE_URL}/${KEY}" >> "$GITHUB_OUTPUT"

      - name: Comment URL on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const url = `${{ toJSON(steps.upload.outputs.url) }}`
            const body = `Built PDF: ${url}`
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            })
